replicaCount: 1

image:
  repository: 716189571315.dkr.ecr.us-east-1.amazonaws.com/cicd-first-tf
  tag: "9eb851a"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

probes:
  liveness:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 5
  readiness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 5

# Extra label so UI me dikhe
envName: "STAGING"
