apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-first-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AmitTheHacker/cicd-eks-project # my GitHub URL
    targetRevision: HEAD
    path: helm/cicd-first
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
